server:
  port: 8080

spring:
  application:
    name: producter
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/message?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useAffectedRows=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 2
      max-active: 10
      initial-size: 4
      max-wait: 600
      validation-query: SELECT 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: test
    connection-timeout: 15000
    publisher-returns: true # 开启return
    publisher-confirm-type: correlated #开启confirm
    # 在此开启会导致return 机制失效 ，请手动开启
    # template:
    #   mandatory: true #消息投递到broker失败后，不立即删除

mybatis:
  type-aliases-package: ink.cwblog.producter.model
  mapper-locations: classpath:sqlclient/*.xml
